// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RDProject.Common;

namespace RDProject.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20220504021625_add_fieldindex")]
    partial class add_fieldindex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RDProject.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("EmpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("UserGroup")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.HasIndex("Name");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("RDProject.Models.Trial", b =>
                {
                    b.Property<long>("FHeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FAssemblyFactory")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("FAssemblyNPI")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("FBillNo")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("FCNCNPI")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("FCoatingNPI")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("FCompany")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<DateTime>("FCreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 5, 4, 10, 16, 24, 790, DateTimeKind.Local).AddTicks(8362));

                    b.Property<string>("FCreateUser")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<DateTime>("FDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FHasAssembly")
                        .HasColumnType("bit");

                    b.Property<bool>("FHasCNC")
                        .HasColumnType("bit");

                    b.Property<bool>("FHasCoating")
                        .HasColumnType("bit");

                    b.Property<bool>("FHasLaser")
                        .HasColumnType("bit");

                    b.Property<string>("FInformation")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("FLaserNPI")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<string>("FProductName")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("FRDNo")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("FRequire")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("FStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FTitle")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("FWorkerOrderDescription")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.HasKey("FHeadId");

                    b.HasIndex("FCompany");

                    b.HasIndex("FCreateDate");

                    b.HasIndex("FCreateUser");

                    b.HasIndex("FDate");

                    b.HasIndex("FProductName");

                    b.HasIndex("FRDNo");

                    b.HasIndex("FStatus");

                    b.HasIndex("FTitle");

                    b.ToTable("Trial");
                });

            modelBuilder.Entity("RDProject.Models.TrialEntry", b =>
                {
                    b.Property<long>("FEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FAmount")
                        .HasColumnType("int");

                    b.Property<DateTime>("FBeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FCreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 5, 4, 10, 16, 24, 790, DateTimeKind.Local).AddTicks(8362));

                    b.Property<DateTime>("FEndDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("FHeadId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("FManHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FManPower")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FProcessName")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<string>("FWorkOrder")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("FEntryId");

                    b.HasIndex("FHeadId");

                    b.HasIndex("FProcessName");

                    b.HasIndex("FWorkOrder");

                    b.ToTable("TrialEntry");
                });

            modelBuilder.Entity("RDProject.Models.WFInstance", b =>
                {
                    b.Property<long>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("HeadId")
                        .HasColumnType("bigint");

                    b.Property<string>("InstanceGuid")
                        .HasColumnType("nvarchar(64)")
                        .HasMaxLength(64);

                    b.Property<string>("NextName")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("SubBy")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<DateTime>("SubTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2022, 5, 4, 10, 16, 24, 778, DateTimeKind.Local).AddTicks(8366));

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("InstanceId");

                    b.HasIndex("HeadId");

                    b.HasIndex("InstanceGuid");

                    b.HasIndex("NextName");

                    b.HasIndex("Status");

                    b.HasIndex("SubBy");

                    b.HasIndex("TableName");

                    b.HasIndex("Status", "NextName");

                    b.ToTable("WFInstance");
                });

            modelBuilder.Entity("RDProject.Models.WFStep", b =>
                {
                    b.Property<long>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BookMark")
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<long>("InstanceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Remark")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("StepNo")
                        .HasColumnType("int");

                    b.Property<string>("SubBy")
                        .HasColumnType("nvarchar(16)")
                        .HasMaxLength(16);

                    b.Property<DateTime?>("SubTime")
                        .HasColumnType("datetime2");

                    b.HasKey("StepId");

                    b.HasIndex("BookMark");

                    b.HasIndex("InstanceId");

                    b.HasIndex("Status");

                    b.HasIndex("SubBy");

                    b.ToTable("WFStep");
                });
#pragma warning restore 612, 618
        }
    }
}
